#!/bin/bash
# Wrapper for Daily Monitoring (Dockerized)
# Generated by Antigravity

PROJECT_DIR="/home/ubuntu/Philly-P-Sniper"
LOG_FILE="$PROJECT_DIR/logs/cron_monitor.log"

cd "$PROJECT_DIR" || exit 1

echo "[$(date)] Starting Monitor..." >> "$LOG_FILE"
sudo docker exec philly_p_api python3 scripts/ops.py monitor >> "$LOG_FILE" 2>&1
