#!/bin/bash
# Wrapper for Daily Scoring (Dockerized)
# Generated by Antigravity

PROJECT_DIR="/home/ubuntu/Philly-P-Sniper"
LOG_FILE="$PROJECT_DIR/logs/cron_scoring.log"

cd "$PROJECT_DIR" || exit 1

echo "--- Starting Daily Scoring for $(date) ---" >> "$LOG_FILE"

# 1. Validation
echo "Step 1: Validation" >> "$LOG_FILE"
sudo docker exec philly_p_api python3 scripts/ops.py validate >> "$LOG_FILE" 2>&1
if [ $? -ne 0 ]; then
    echo "❌ Validation Failed. Aborting Scoring." >> "$LOG_FILE"
    exit 1
fi

# 2. Scoring
echo "Step 2: Scoring" >> "$LOG_FILE"
sudo docker exec philly_p_api python3 scripts/ops.py score >> "$LOG_FILE" 2>&1
echo "[$(date)] Scoring Complete (Exit: $?)" >> "$LOG_FILE"
