#!/bin/bash
# Wrapper for Daily Ingestion (Dockerized)
# Generated by Antigravity

PROJECT_DIR="/home/ubuntu/Philly-P-Sniper"
LOG_FILE="$PROJECT_DIR/logs/cron_ingest.log"

cd "$PROJECT_DIR" || exit 1

echo "[$(date)] Starting Ingest (Docker)..." >> "$LOG_FILE"
# Execute inside named container 'philly_p_api'
sudo docker exec philly_p_api python3 scripts/ops.py ingest >> "$LOG_FILE" 2>&1
echo "[$(date)] Ingest Complete (Exit: $?)" >> "$LOG_FILE"
