#!/bin/bash
# Wrapper for Hourly Edge Recommendations (Dockerized)
# Generated by Antigravity

PROJECT_DIR="/home/ubuntu/Philly-P-Sniper"
LOG_FILE="$PROJECT_DIR/logs/cron_edge.log"

cd "$PROJECT_DIR" || exit 1

sudo docker exec philly_p_api python3 scripts/ops.py recommend >> "$LOG_FILE" 2>&1
