#!/bin/bash
# Wrapper for Daily Settlement (Dockerized)
# Generated by Antigravity

PROJECT_DIR="/home/ubuntu/Philly-P-Sniper"
LOG_FILE="$PROJECT_DIR/logs/cron_settle.log"

cd "$PROJECT_DIR" || exit 1

echo "[$(date)] Starting Settlement..." >> "$LOG_FILE"
sudo docker exec philly_p_api python3 scripts/settle_bets.py >> "$LOG_FILE" 2>&1
