#!/bin/bash
# Cron Deployment Script
# Generated by Antigravity
# Usage: ./scripts/deploy_cron.sh

# 1. Config
USER="ubuntu"
PROJECT_DIR="/home/ubuntu/Philly-P-Sniper"
WRAPPER_DIR="$PROJECT_DIR/scripts/wrappers"
LOG_DIR="$PROJECT_DIR/logs"

# 2. Safety Checks
if [ "$(id -un)" != "$USER" ]; then
    echo "⚠️  Warning: Running as $(id -un), expected $USER. Cron might be installed for wrong user."
fi

if [[ "$PWD" != *Philly-P-Sniper ]]; then
    echo "⚠️  Please run from Project Root (Philly-P-Sniper)."
fi

# 3. Setup
echo "📂 Creating Log Directory: $LOG_DIR"
mkdir -p "$LOG_DIR"

echo "🔧 Setting Permissions..."
chmod +x "$WRAPPER_DIR"/*.sh

# 4. Define Crontab
# Check for existing block to avoid duplication?
# The block is delimited by the header.
HEADER="# --- PHILLY-P-SNIPER AUTOMATION ---"

# Cron Schedule
# 08:00 Ingest
# 08:15 Settlement (Yesterday's bets)
# 09:00 Score (Validate + Projections)
# 17:00, 18:00 Edge Engine (5PM, 6PM ET) - Assumes Server is ET or UTC Adjustment
# 23:30 Monitor

CRON_BLOCK="$HEADER
# Daily Ingest (08:00 AM)
0 8 * * * $WRAPPER_DIR/run_daily_ingest.sh

# Daily Settlement (08:15 AM - After Ingest)
15 8 * * * $WRAPPER_DIR/run_settlement.sh

# Daily Scoring (09:00 AM)
0 9 * * * $WRAPPER_DIR/run_daily_scoring.sh

# Edge Engine (5:00 PM, 6:00 PM Eastern)
0 17,18 * * * $WRAPPER_DIR/run_edge_hourly.sh

# Daily Monitoring (11:30 PM)
30 23 * * * $WRAPPER_DIR/run_daily_monitor.sh
# ------------------------------------------"

# 5. Install
echo "📝 Updating Crontab..."

# Get current crontab, remove old block, append new block
CURRENT_CRON=$(crontab -l 2>/dev/null)
# Clean old script refs
CLEAN_CRON=$(echo "$CURRENT_CRON" | grep -v "run_daily_ingest" | grep -v "run_daily_scoring" | grep -v "run_edge_hourly" | grep -v "run_daily_monitor" | grep -v "run_settlement" | grep -v "$HEADER")

# Combine
NEW_CRON="$CLEAN_CRON
$CRON_BLOCK"

echo "$NEW_CRON" | crontab -

echo "✅ [DEPLOY-CRON] Success! Current Crontab:"
crontab -l
